[[pages]]
path = "main.py"
name = "Home"

[[pages]]
path = "paginas/estatisticas.py"
name = "Estatisticas"

[[pages]]
path = "paginas/eletrico.py"
name = "Eletrico"

[[pages]]
path = "paginas/sobre.py"
name = "Sobre"